version: '3'
services:
  config-server:
    container_name: config-server
    image: amenezes/spring-cloud-configserver
    ports:
      - 8888:8888
  # config-client:
  #   container_name: config-client
  #   build:
  #     context: .
  #   command:
  #     - client
  #     - -h
